### ISSUE TITLE
First time install of Craft fails

### ISSUE THREAD

**Issue by Baynrich** [netliferesearch/craft-starter#91]
```    
    > can't apply existing project config: Craft is installed at the wrong schema version (3.6.8, but project.yaml lists ).
    > moving config/project/ to storage/config-backups/project-2021-08-17-195053 ... Exception: rename(): The first argument to copy() function cannot be a directory (/var/www/html/vendor/craftcms/cms/src/migrations/Install.php:1091)
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'rename(): The f...', '/var/www/html/v...', 1091)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'rename(): The f...', '/var/www/html/v...', 1091, Array)
#2 /var/www/html/vendor/craftcms/cms/src/migrations/Install.php(1091): rename('/var/www/html/c...', '/var/www/html/s...')
#3 /var/www/html/vendor/craftcms/cms/src/migrations/Install.php(74): craft\migrations\Install->insertDefaultData()
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\Install->safeUp()
#5 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#6 /var/www/html/vendor/craftcms/cms/src/controllers/InstallController.php(300): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#7 [internal function]: craft\controllers\InstallController->actionInstall()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('install', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('install', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction('install/install', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application->runAction('install/install', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(543): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(187): craft\web\Application->_processInstallRequest(Object(craft\web\Request))
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/html/public/index.php(21): yii\base\Application->run()
#18 {main}
```

**Comment by timharek** [comment]
I'm able to get to the Craft install page on [http://localhost:5000/admin/install](http://localhost:5000/admin/install) just fine.
But I get an error when installing.
<details>

<summary>Picture of error</summary>

![image](https://user-images.githubusercontent.com/5453010/131644254-4d0347ab-ac00-49aa-8822-982ffc9c7781.png)


</details>

When I check my logs in `/storage/web.log` it seems that `craft_cms.craft_info` doesn't exist as this error is mentioned alot in this log.

```log
2021-09-01 09:00:24 [-][-][-][error][yii\db\Exception] PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft_cms.craft_info' doesn't exist in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1302
```

Also, there is a mention of this instance using the wrong schema version in `project.yaml`
```log
2021-09-01 09:00:37 [-][-][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Craft is installed at the wrong schema version (3.6.8, but project.yaml lists ). in /var/www/html/vendor/craftcms/cms/src/migrations/Install.php:1075
```

Could this have something to do with permissions?

**Comment by timharek** [comment]
I have currently tried the following:

1. Specifying the `platform` in `docker-compose.yml` on both the `server` and `database`.
	- `platform: linux/x86_64`
2. Specifying the platform in `Dockerfile`.
	- `FROM --platform=linux/x86_64 php:7.4-apache`
3. Running `composer install` directly inside the Docker-container.
4. Running `./craft install` directly inside the Docker-container.

**Comment by timharek** [comment]
I managed to get it working now.

The current state the repo is in is not working for some reason, I checked out in 7e81abb6d4752f644d682c67d138c5b0dc6f738d and ran

```sh
npm install
npm run composer update && npm run composer install
docker-compose up
```

I tried to do this in a15f1c5806cf252e6be63f7a14b1fd04f367fcaf, but it doesn't work for some reason.

Opening a PR with a fix for this.

**Comment by timharek** [comment]
I have tried to update Craft to `3.6.17` and `3.7.11`, both times I've gotten an error.

I can see in the logs the following:
```
server_1    | 172.30.0.1 - - [08/Sep/2021:10:38:13 +0000] "POST /index.php?p=admin/actions/install/validate-account HTTP/1.1" 200 470 "http://localhost:5000/admin/install" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0"
```

I suspect that Craft now does some kind of verification, and it seems like it doesn't go through.
